"""RiverMind's normalized poker hand-history core."""

from .coach import (
    COACH_CANDIDATE_SCHEMA_VERSION,
    COACH_EVIDENCE_SCHEMA_VERSION,
    COACH_TEMPLATE_VERSION,
    CandidateValidation,
    CoachCandidate,
    CoachExplanation,
    CoachItem,
    CoachReport,
    CoachSource,
    EvidenceFact,
    ExplanationEvidence,
    ValidationIssue,
    ValidationStatus,
    build_explanation_evidence,
    coach_report_to_dict,
    explain_leak_card,
    explain_leak_report,
    validate_coach_candidate,
)
from .accounting import (
    ActionLedgerEntry,
    HandAccountingError,
    HandLedger,
    PlayerHandResult,
    calculate_hand_ledger,
    calculate_action_ledger,
)

from .models import (
    Action,
    ActionType,
    BettingRound,
    GameType,
    HandHistory,
    HandValidationError,
    Player,
    PlayerPosition,
    enrich_player_context,
)
from .importer import (
    HandHistoryImporter,
    ImportBatchReport,
    ImportItemResult,
    ImportItemStatus,
    split_hand_histories,
)
from .leaks import (
    DEFAULT_LEAK_RULES,
    LEAK_PROFILE_ID,
    LEAK_PROFILE_VERSION,
    LeakAssessment,
    LeakCard,
    LeakDirection,
    LeakReport,
    LeakRule,
    LeakSeverity,
    LeakStatus,
    build_leak_report,
    evaluate_leaks,
    wilson_interval_95,
)
from .storage import SQLiteHandStore
from .sessions import (
    PlayerHandOutcome,
    SessionSummary,
    build_player_hand_outcomes,
    parse_played_at,
    summarize_sessions,
)
from .replay import (
    HandReplay,
    ReplayFrame,
    ReplayPlayer,
    build_hand_replay,
)
from .reports import (
    HandQuery,
    PlayerHandReport,
    StatMetric,
)
from .html_report import render_analysis_page
from .stats import (
    PlayerHandStatRow,
    PlayerStats,
    StatValue,
    StatsFilter,
    aggregate_player_stat_rows,
    build_player_hand_stat_rows,
    calculate_player_stats,
)

__all__ = [
    "Action",
    "ActionLedgerEntry",
    "ActionType",
    "BettingRound",
    "COACH_CANDIDATE_SCHEMA_VERSION",
    "COACH_EVIDENCE_SCHEMA_VERSION",
    "COACH_TEMPLATE_VERSION",
    "CandidateValidation",
    "CoachCandidate",
    "CoachExplanation",
    "CoachItem",
    "CoachReport",
    "CoachSource",
    "EvidenceFact",
    "ExplanationEvidence",
    "GameType",
    "HandHistory",
    "HandAccountingError",
    "HandLedger",
    "HandReplay",
    "HandQuery",
    "HandHistoryImporter",
    "HandValidationError",
    "ImportBatchReport",
    "ImportItemResult",
    "ImportItemStatus",
    "LEAK_PROFILE_ID",
    "LEAK_PROFILE_VERSION",
    "DEFAULT_LEAK_RULES",
    "LeakAssessment",
    "LeakCard",
    "LeakDirection",
    "LeakReport",
    "LeakRule",
    "LeakSeverity",
    "LeakStatus",
    "Player",
    "PlayerPosition",
    "PlayerHandStatRow",
    "PlayerHandResult",
    "PlayerHandReport",
    "PlayerHandOutcome",
    "PlayerStats",
    "ReplayFrame",
    "ReplayPlayer",
    "SQLiteHandStore",
    "SessionSummary",
    "StatValue",
    "StatsFilter",
    "StatMetric",
    "ValidationIssue",
    "ValidationStatus",
    "aggregate_player_stat_rows",
    "build_player_hand_stat_rows",
    "build_player_hand_outcomes",
    "build_hand_replay",
    "build_explanation_evidence",
    "build_leak_report",
    "calculate_player_stats",
    "coach_report_to_dict",
    "calculate_action_ledger",
    "calculate_hand_ledger",
    "enrich_player_context",
    "explain_leak_card",
    "explain_leak_report",
    "evaluate_leaks",
    "parse_played_at",
    "render_analysis_page",
    "summarize_sessions",
    "split_hand_histories",
    "wilson_interval_95",
    "validate_coach_candidate",
]
